# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-25 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_bloodtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livertest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgot', models.CharField(max_length=200)),
                ('sgpt', models.CharField(max_length=200)),
                ('albumin', models.CharField(max_length=200)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.Patient')),
            ],
        ),
    ]
